version: "3"
services:
  db:
    image: postgres:11
    container_name: pgsql11
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_EXTRA_OPTS= '--schema=public --blobs'

volumes:
  db-data:
    driver: local

networks:
  backend:  
    name: backend

