{%- if env == 'QA' or env == 'PROD' -%}
FROM wso2qa4.ccu.cl:5000/pos-odoo-img

# Set default user when running the container
#USER root

COPY config             /etc/odoo
COPY src/custom-addons  /mnt/extra-addons/custom-addons

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/odoo/odoo.log

ENTRYPOINT ["/entrypoint.sh"]
CMD ["odoo"]

{%- else -%}
FROM odoo:14.0

# Set default user when running the container
USER root

# Install some deps, lessc and less-plugin-clean-css, and wkhtmltopdf
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    python3-cachetools

# Install python libraries for base rest
RUN python3 -m pip install --force-reinstall pip setuptools
RUN apt-get install -y python3-openssl

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/odoo/odoo.log

RUN ["chmod", "+x", "/entrypoint.sh"]
RUN ["chmod", "+x", "/usr/local/bin/wait-for-psql.py"]
{%- endif %}