version: '3'
services:
  web:
    image: odoo-pos
    container_name: odoo

    user: root
    ports:
      - 8069:8069
    build:
      context: .
      dockerfile: Dockerfile 
    networks:
      - frontend
      - backend

    entrypoint: ['/entrypoint.sh', 'odoo']      
    volumes:
      - ./config:/etc/odoo
      - ./enterprise:/mnt/enterprise
      - ./src/custom-addons:/mnt/extra-addons/custom-addons

  nginx:     
    container_name: nginx
    restart: unless-stopped
    image: nginx:latest
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-config/nginx_template.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/private.key:/etc/nginx/ssl/key/ccu.cl.key
      - ./nginx/ssl/public.cer:/etc/nginx/ssl/crt/ccu.cl.cer

networks:
  frontend:
      name: frontend

  backend:
    external:
      name: backend
